# Generated by Django 3.2.12 on 2022-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('adidas', 'Adidas'), ('puma', 'Puma'), ('nike', 'Nike'), ('jordan', 'Jordan'), ('champion', 'Champion'), ('elesse', 'Elesse')], max_length=255, null=True),
        ),
    ]
