# Generated by Django 3.2.12 on 2022-04-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('adidas', 'Adidas'), ('puma', 'Puma'), ('nike', 'Nike'), ('jordan', 'Jordan'), ('champion', 'Champion'), ('elesse', 'Elesse'), ('47-brand', '47 Brand')], max_length=255, null=True),
        ),
    ]
