# Generated by Django 3.2.12 on 2022-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_viewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
