# Generated by Django 3.2.12 on 2022-04-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_times_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
