# Generated by Django 3.2.12 on 2022-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_brand'),
        ('carts', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
