# Generated by Django 3.2.12 on 2022-04-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_testmodel_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
